import type { Order, CatalogProduct, CreateProductFormValues } from "../types";

export const CATALOG_STORAGE_KEY = "trophy-admin-catalog";

export const collectionOptions = ["Summer Drop", "Core Essentials", "Travel Edit", "Editorial Spotlight"];
export const categoryOptions = ["Outerwear", "Tops", "Accessories", "Knitwear", "Headwear", "Footwear"];

export const initialOrders: Order[] = [
  {
    id: "#1001",
    customer: "Lena Howard",
    status: "Pending",
    total: 124,
    items: 3,
    date: "2026-06-21",
    channel: "Web",
    email: "lena@example.com",
    paymentStatus: "Authorized",
    fulfillmentStatus: "Unfulfilled",
    shippingAddress: "120 Hudson St, New York, NY 10013",
    billingAddress: "120 Hudson St, New York, NY 10013",
    paymentMethod: "Visa ending in 4242",
    lineItems: [
      { title: "Core Box Tee", quantity: 2, unitPrice: 28, variant: "Black / M" },
      { title: "Signature Field Cap", quantity: 1, unitPrice: 32, variant: "Olive" },
    ],
    timeline: [
      { at: "2026-06-21 09:14", title: "Order placed", detail: "Customer completed checkout on web storefront." },
      { at: "2026-06-21 09:17", title: "Payment authorized", detail: "Card authorization approved and awaiting capture." },
    ],
  },
  {
    id: "#1002",
    customer: "Marcus Chen",
    status: "Processing",
    total: 248,
    items: 5,
    date: "2026-06-21",
    channel: "Draft order",
    email: "marcus@example.com",
    paymentStatus: "Captured",
    fulfillmentStatus: "Partially fulfilled",
    shippingAddress: "14 Orchard Rd, Singapore 238825",
    billingAddress: "14 Orchard Rd, Singapore 238825",
    paymentMethod: "Manual invoice",
    lineItems: [
      { title: "Trophy Heavyweight Hoodie", quantity: 2, unitPrice: 68, variant: "Heather / L" },
      { title: "Core Box Tee", quantity: 3, unitPrice: 28, variant: "White / XL" },
    ],
    timeline: [
      { at: "2026-06-21 08:40", title: "Draft order created", detail: "Operator created draft order for wholesale customer." },
      { at: "2026-06-21 08:55", title: "Payment captured", detail: "Bank transfer marked as received." },
      { at: "2026-06-21 10:20", title: "Partial fulfillment", detail: "Two hoodie units handed to warehouse." },
    ],
  },
  {
    id: "#1003",
    customer: "Sofia Tran",
    status: "Fulfilled",
    total: 86,
    items: 2,
    date: "2026-06-20",
    channel: "Web",
    email: "sofia@example.com",
    paymentStatus: "Captured",
    fulfillmentStatus: "Fulfilled",
    shippingAddress: "93 Le Loi, Ho Chi Minh City",
    billingAddress: "93 Le Loi, Ho Chi Minh City",
    paymentMethod: "Mastercard ending in 1188",
    lineItems: [{ title: "Merino Travel Crew", quantity: 1, unitPrice: 54, variant: "Navy / M" }, { title: "Signature Field Cap", quantity: 1, unitPrice: 32, variant: "Black" }],
    timeline: [
      { at: "2026-06-20 13:15", title: "Order placed", detail: "Customer completed checkout." },
      { at: "2026-06-20 13:20", title: "Payment captured", detail: "Payment settled immediately." },
      { at: "2026-06-20 17:40", title: "Fulfilled", detail: "Shipment handed to carrier." },
    ],
  },
  {
    id: "#1004",
    customer: "Noah Rivera",
    status: "Canceled",
    total: 159,
    items: 4,
    date: "2026-06-20",
    channel: "Manual",
    email: "noah@example.com",
    paymentStatus: "Canceled",
    fulfillmentStatus: "Canceled",
    shippingAddress: "55 Market St, San Francisco, CA 94105",
    billingAddress: "55 Market St, San Francisco, CA 94105",
    paymentMethod: "Invoice canceled",
    lineItems: [{ title: "Canvas Utility Tote", quantity: 4, unitPrice: 24, variant: "Default" }],
    timeline: [
      { at: "2026-06-20 12:00", title: "Order created", detail: "Manual order created by support." },
      { at: "2026-06-20 14:10", title: "Order canceled", detail: "Customer changed requirements before capture." },
    ],
  },
  {
    id: "#1005",
    customer: "Avery Patel",
    status: "Processing",
    total: 412,
    items: 8,
    date: "2026-06-19",
    channel: "Web",
    email: "avery@example.com",
    paymentStatus: "Captured",
    fulfillmentStatus: "Partially fulfilled",
    shippingAddress: "22 Connaught Pl, New Delhi 110001",
    billingAddress: "22 Connaught Pl, New Delhi 110001",
    paymentMethod: "Amex ending in 2001",
    lineItems: [{ title: "Trophy Heavyweight Hoodie", quantity: 4, unitPrice: 68, variant: "Stone / L" }, { title: "Core Box Tee", quantity: 4, unitPrice: 28, variant: "Black / L" }],
    timeline: [
      { at: "2026-06-19 16:45", title: "Order placed", detail: "Customer completed checkout." },
      { at: "2026-06-19 16:50", title: "Payment captured", detail: "Charge settled." },
      { at: "2026-06-20 09:10", title: "Partial fulfillment", detail: "Warehouse packed half the line items." },
    ],
  },
  {
    id: "#1006",
    customer: "Ivy Nguyen",
    status: "Fulfilled",
    total: 74,
    items: 1,
    date: "2026-06-18",
    channel: "Instagram",
    email: "ivy@example.com",
    paymentStatus: "Captured",
    fulfillmentStatus: "Fulfilled",
    shippingAddress: "7 Tran Hung Dao, Da Nang",
    billingAddress: "7 Tran Hung Dao, Da Nang",
    paymentMethod: "Manual payment link",
    lineItems: [{ title: "Merino Travel Crew", quantity: 1, unitPrice: 54, variant: "Charcoal / M" }],
    timeline: [
      { at: "2026-06-18 11:05", title: "Manual order created", detail: "Social commerce order entered by operator." },
      { at: "2026-06-18 11:20", title: "Payment captured", detail: "Payment link settled." },
      { at: "2026-06-18 15:05", title: "Fulfilled", detail: "Package dispatched." },
    ],
  },
];

export const initialProducts: CatalogProduct[] = [
  {
    id: "prod_hoodie",
    title: { vi: "Trophy Heavyweight Hoodie", en: "" },
    handle: "trophy-heavyweight-hoodie",
    subtitle: { vi: "Signature seasonal fleece", en: "" },
    description: { vi: "Heavyweight brushed fleece hoodie for editorial drops.", en: "" },
    status: "Published",
    inventory: 48,
    price: 68,
    category: "Outerwear",
    collection: "Core Essentials",
    collectionId: null,
    categories: ["Outerwear"],
    categoryIds: [],
    media: [],
    attributes: [{ key: "Fabric", value: "430gsm cotton blend" }],
    optionDefinitions: [],
    variants: [
      {
        id: "var_hoodie_default",
        title: "Default variant",
        sku: "TR-HOODIE-001",
        price: 68,
        inventory: 48,
        options: [],
        allowBackorder: false,
        media: [],
        shouldCreate: true,
      },
    ],
    updatedAt: "2026-06-21",
  },
  {
    id: "prod_cap",
    title: { vi: "Signature Field Cap", en: "" },
    handle: "signature-field-cap",
    subtitle: { vi: "Low-profile six-panel cap", en: "" },
    description: { vi: "Cotton twill cap with stitched emblem.", en: "" },
    status: "Published",
    inventory: 6,
    price: 32,
    category: "Accessories",
    collection: "Travel Edit",
    collectionId: null,
    categories: ["Accessories", "Headwear"],
    categoryIds: [],
    media: [],
    attributes: [{ key: "Closure", value: "Adjustable strap" }],
    optionDefinitions: [],
    variants: [
      {
        id: "var_cap_default",
        title: "Default variant",
        sku: "TR-CAP-001",
        price: 32,
        inventory: 6,
        options: [],
        allowBackorder: false,
        media: [],
        shouldCreate: true,
      },
    ],
    updatedAt: "2026-06-21",
  },
  {
    id: "prod_shirt",
    title: { vi: "Core Box Tee", en: "" },
    handle: "core-box-tee",
    subtitle: { vi: "Relaxed staple tee", en: "" },
    description: { vi: "Structured cotton jersey tee with broad fit.", en: "" },
    status: "Published",
    inventory: 124,
    price: 28,
    category: "Tops",
    collection: "Core Essentials",
    collectionId: null,
    categories: ["Tops"],
    categoryIds: [],
    media: [],
    attributes: [{ key: "Fit", value: "Relaxed" }],
    optionDefinitions: [],
    variants: [
      {
        id: "var_shirt_default",
        title: "Default variant",
        sku: "TR-TEE-001",
        price: 28,
        inventory: 124,
        options: [],
        allowBackorder: false,
        media: [],
        shouldCreate: true,
      },
    ],
    updatedAt: "2026-06-20",
  },
  {
    id: "prod_tote",
    title: { vi: "Canvas Utility Tote", en: "" },
    handle: "canvas-utility-tote",
    subtitle: { vi: "Merchandising prototype", en: "" },
    description: { vi: "Draft carry-all for upcoming release.", en: "" },
    status: "Draft",
    inventory: 0,
    price: 24,
    category: "Accessories",
    collection: "Editorial Spotlight",
    collectionId: null,
    categories: ["Accessories"],
    categoryIds: [],
    media: [],
    attributes: [{ key: "Capacity", value: "18L" }],
    optionDefinitions: [],
    variants: [
      {
        id: "var_tote_default",
        title: "Default variant",
        sku: "TR-TOTE-001",
        price: 24,
        inventory: 0,
        options: [],
        allowBackorder: false,
        media: [],
        shouldCreate: true,
      },
    ],
    updatedAt: "2026-06-19",
  },
  {
    id: "prod_crew",
    title: { vi: "Merino Travel Crew", en: "" },
    handle: "merino-travel-crew",
    subtitle: { vi: "Light knit layer", en: "" },
    description: { vi: "Travel-ready knitwear with packable warmth.", en: "" },
    status: "Published",
    inventory: 22,
    price: 54,
    category: "Knitwear",
    collection: "Travel Edit",
    collectionId: null,
    categories: ["Knitwear"],
    categoryIds: [],
    media: [],
    attributes: [{ key: "Material", value: "Merino wool blend" }],
    optionDefinitions: [],
    variants: [
      {
        id: "var_crew_default",
        title: "Default variant",
        sku: "TR-CREW-001",
        price: 54,
        inventory: 22,
        options: [],
        allowBackorder: false,
        media: [],
        shouldCreate: true,
      },
    ],
    updatedAt: "2026-06-18",
  },
];

export const defaultCreateProductValues: CreateProductFormValues = {
  title: { vi: "", en: "" },
  handle: "",
  subtitle: { vi: "", en: "" },
  description: { vi: "", en: "" },
  customizationEnabled: false,
  collection: "",
  categories: [],
  media: "",
  hasVariants: false,
  basePrice: "",
  inventory: "",
  optionNameOne: "",
  optionValuesOne: "",
  optionNameTwo: "",
  optionValuesTwo: "",
};
