export default {
  theme: {
    extend: {
      "colors": {
          "brand-hero": "#171740",
          "brand-strong": "#244159",
          "brand-support": "#288ab6",
          "brand-accent": "#04a387",
          "text-strong": "#244159",
          "text-base": "#232323",
          "text-muted": "#717171",
          "text-on-dark": "#ffffff",
          "surface-base": "#ffffff",
          "surface-subtle": "#f5f5f5",
          "surface-panel": "#f8f8f8",
          "surface-dark": "#171740",
          "border-subtle": "#e5e5e5",
          "border-strong": "#244159",
          "action-support": "#288ab6",
          "action-support-hover": "#226f92",
          "action-positive": "#04a387",
          "action-positive-hover": "#038a72",
          "action-commerce": "#ea4222",
          "action-commerce-hover": "#d23a1d",
          "indicator-trust": "#04a387",
          "indicator-support": "#288ab6",
          "indicator-price": "#ea4222",
          "indicator-rating": "#f6d02b",
          "primary-fixed-dim": "#288ab6",
          "surface-tint": "#171740",
          "outline": "#d7d7d7",
          "tertiary-fixed-dim": "#c6c6c6",
          "on-tertiary": "#ffffff",
          "surface-container-low": "#f8f8f8",
          "secondary-container": "#e9f7f4",
          "surface-container-high": "#efefef",
          "tertiary-fixed": "#e2e2e2",
          "on-primary-container": "#ffffff",
          "surface-variant": "#f4f4f4",
          "on-secondary-fixed": "#1a1c1c",
          "on-secondary-fixed-variant": "#454747",
          "primary-fixed": "#171740",
          "secondary-fixed": "#e2e2e2",
          "secondary-fixed-dim": "#c6c6c7",
          "on-error-container": "#93000a",
          "on-surface-variant": "#6b7280",
          "on-surface": "#232323",
          "inverse-on-surface": "#f3f0ef",
          "surface": "#ffffff",
          "on-secondary-container": "#232323",
          "inverse-primary": "#288ab6",
          "on-secondary": "#232323",
          "tertiary-container": "#e8f1f7",
          "error": "#ba1a1a",
          "surface-container": "#f5f5f5",
          "primary-container": "#04a387",
          "outline-variant": "#e5e5e5",
          "secondary": "#f5f5f5",
          "primary": "#244159",
          "surface-dim": "#ebebeb",
          "tertiary": "#288ab6",
          "surface-container-lowest": "#ffffff",
          "error-container": "#ffdad6",
          "on-tertiary-fixed-variant": "#454747",
          "on-error": "#ffffff",
          "on-primary-fixed": "#ffffff",
          "on-tertiary-fixed": "#1a1c1c",
          "on-primary-fixed-variant": "#ffffff",
          "on-primary": "#ffffff",
          "on-tertiary-container": "#244159",
          "on-background": "#232323",
          "surface-bright": "#ffffff",
          "surface-container-highest": "#e5e5e5",
          "inverse-surface": "#313030",
          "background": "#ffffff"
      },
      "borderRadius": {
          "sm":      "0.25rem",
          "DEFAULT": "0.5rem",
          "md":      "0.75rem",
          "lg":      "1rem",
          "xl":      "1.5rem",
          "full":    "9999px"
      },
      "spacing": {
          "gutter":           "24px",
          "base":             "8px",
          "container-max":    "1280px",
          "margin-mobile":    "16px",
          "margin-desktop":   "64px"
      },
      "fontFamily": {
          "headline-lg": ["Koulen"],
          "label-md": ["Open Sans"],
          "display-lg-mobile": ["Koulen"],
          "headline-md": ["Koulen"],
          "display-lg": ["Koulen"],
          "body-md": ["Open Sans"],
          "body-lg": ["Open Sans"]
      },
      "fontSize": {
          "headline-lg":       ["40px", {"lineHeight": "44px", "letterSpacing": "0.02em", "fontWeight": "400"}],
          "label-md":          ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
          "display-lg-mobile": ["48px", {"lineHeight": "48px", "letterSpacing": "0.04em", "fontWeight": "400"}],
          "headline-md":       ["32px", {"lineHeight": "36px", "letterSpacing": "0.02em", "fontWeight": "400"}],
          "display-lg":        ["72px", {"lineHeight": "72px", "letterSpacing": "0.04em", "fontWeight": "400"}],
          "body-md":           ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "body-lg":           ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    }
  }
}
